#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🎨🧑‍🎨 Styling your project before committing'

npm run check-format || (
  echo '🚨🚨 Styling check failed. 
        Run npm run format, add changes and commit again.';
  false;
)

echo '👍👍 Styling passed. Ready to commit'